import os
import tempfile
from collections import Counter
try:
    from rdkit import Chem
    from rdkit.Chem.Scaffolds import MurckoScaffold
    from rdkit.Chem import Draw
    RDKIT_AVAILABLE = True
except ImportError:
    RDKIT_AVAILABLE = False

class PDFReport(FPDF):
    def __init__(self, logo_path="assets/logo.png", title="QSAR Modeling Report"):
        super().__init__()
        self.logo_path = logo_path
        self.report_title = title
        
    def header(self):
        # Logo
        if os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 33)
            
        # Arial bold 15
        self.set_font('Arial', 'B', 15)
        # Move to the right
        self.cell(80)
        # Title
        self.cell(80, 10, self.report_title, 0, 0, 'C')
        # Line break
        self.ln(20)
        # Line separator
        self.set_draw_color(0, 80, 180) # Professional Blue
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb} | Generated by QSAR Data Curation Tool', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255) # Light blue fill
        self.cell(0, 6, f"  {label}", 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, text)
        self.ln()
        
    def add_metric_card(self, label, value):
        self.set_font('Arial', 'B', 10)
        self.cell(50, 6, label, 0, 0)
        self.set_font('Arial', '', 10)
        self.cell(50, 6, str(value), 0, 1)

def generate_pdf_report(results_df, best_model_name, dataset_stats, logo_path="logo.png", lang="English", roc_plot_path=None, params=None):
    pdf = PDFReport(logo_path=logo_path, title="QSAR Modeling Report")
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Translations for headers
    t = {
        "English": {
            "summary": "1. Executive Summary & Recommendation",
            "best": "Best Model Recommendation:",
            "rationale": "Based on the highest Matthews Correlation Coefficient (MCC), the recommended model is:",
            "dataset": "2. Dataset Information",
            "models": "3. Model Performance Comparison",
            "roc": "4. ROC Curve Analysis",
            "metric": "Metric",
            "value": "Value",
            "params": "Model Configuration",
            "conf_matrix": "Confusion Matrix (Best Model)"
        },
        "Português": {
            "summary": "1. Resumo Executivo e Recomendação",
            "best": "Recomendação de Melhor Modelo:",
            "rationale": "Baseado no maior Índice de Correlação de Matthews (MCC), o modelo recomendado é:",
            "dataset": "2. Informações do Dataset",
            "models": "3. Comparação de Performance dos Modelos",
            "roc": "4. Análise da Curva ROC",
            "metric": "Métrica",
            "value": "Valor",
            "params": "Configuração do Modelo",
            "conf_matrix": "Matriz de Confusão (Melhor Modelo)"
        },
        "Deutsch": {
            "summary": "1. Zusammenfassung & Empfehlung",
            "best": "Empfohlenes Modell:",
            "rationale": "Basierend auf dem höchsten Matthews-Korrelationskoeffizienten (MCC) ist das empfohlene Modell:",
            "dataset": "2. Dataset-Informationen",
            "models": "3. Modellleistungsvergleich",
            "roc": "4. ROC-Kurvenanalyse",
            "metric": "Metrik",
            "value": "Wert",
            "params": "Modellkonfiguration",
            "conf_matrix": "Verwechslungsmatrix (Bestes Modell)"
        }
    }
    
    current_t = t.get(lang, t["English"])
    
    # 1. Executive Summary
    pdf.chapter_title(current_t["summary"])
    
    # Highlight Box for Best Model
    pdf.set_fill_color(240, 255, 240) # Light green
    pdf.set_draw_color(0, 100, 0)
    pdf.rect(10, pdf.get_y(), 190, 25, 'FD')
    
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 5, current_t["best"], 0, 1)
    
    pdf.set_xy(15, pdf.get_y())
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(0, 10, best_model_name, 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    pdf.chapter_body(current_t["rationale"])

    # 1.1 Model Parameters (New)
    if params:
        pdf.ln(5)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, current_t["params"], 0, 1)
        pdf.set_font('Arial', '', 10)
        for k, v in params.items():
            pdf.cell(50, 6, f"{k}:", 0, 0)
            pdf.cell(0, 6, str(v), 0, 1)
        pdf.ln(5)

    # 1.2 Confusion Matrix for Best Model (New)
    # Check if TP/TN/FP/FN exist in df
    best_row = results_df[results_df['Modelo'] == best_model_name].iloc[0] if not results_df[results_df['Modelo'] == best_model_name].empty else None
    
    if best_row is not None and 'TP' in best_row and 'TN' in best_row:
        pdf.ln(5)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, current_t["conf_matrix"], 0, 1)
        
        # Simple Confusion Matrix Table
        #      | Pred 1 | Pred 0
        # True 1 |   TP   |   FN
        # True 0 |   FP   |   TN
        
        tp, tn = int(best_row['TP']), int(best_row['TN'])
        fp, fn = int(best_row['FP']), int(best_row['FN'])
        
        pdf.set_font('Arial', 'B', 10)
        pdf.set_fill_color(230, 230, 230)
        
        # Headers
        pdf.cell(30, 8, "", 0, 0)
        pdf.cell(30, 8, "Pred Active", 1, 0, 'C', 1)
        pdf.cell(30, 8, "Pred Inactive", 1, 1, 'C', 1)
        
        # Row 1 (Actual Active)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(30, 8, "Actual Active", 1, 0, 'C', 1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(30, 8, str(tp), 1, 0, 'C') # TP
        pdf.cell(30, 8, str(fn), 1, 1, 'C') # FN
        
        # Row 2 (Actual Inactive)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(30, 8, "Actual Inactive", 1, 0, 'C', 1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(30, 8, str(fp), 1, 0, 'C') # FP
        pdf.cell(30, 8, str(tn), 1, 1, 'C') # TN
        
        pdf.ln(5)
            
    # 2. Dataset Info
    pdf.chapter_title(current_t["dataset"])
    for key, value in dataset_stats.items():
        pdf.add_metric_card(key, value)
    pdf.ln()
    
    # 3. Model Comparisons Table
    pdf.chapter_title(current_t["models"])
    
    # Table Header
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(200, 200, 200)
    
    # Dynamic columns based on df
    # Select key metrics
    cols = ["Modelo", "Acurácia", "MCC", "F1-Score", "AUC"]
    # Ensure they exist
    cols = [c for c in cols if c in results_df.columns]
    
    col_widths = [50] + [30] * (len(cols)-1)
    
    for i, col in enumerate(cols):
        pdf.cell(col_widths[i], 7, col, 1, 0, 'C', 1)
    pdf.ln()
    
    # Table Rows
    pdf.set_font('Arial', '', 10)
    fill = False
    for index, row in results_df.iterrows():
        # Highlight best model row?
        is_best = row["Modelo"] == best_model_name
        if is_best:
            pdf.set_font('Arial', 'B', 10)
            pdf.set_fill_color(255, 255, 200) # Light yellow highlight
            fill = True
        else:
            pdf.set_font('Arial', '', 10)
            if fill: pdf.set_fill_color(245, 245, 245) # Alternating greys if we want, but let's stick to simple
            fill = False
        
        # If we want alternating rows, we can flip fill boolean
        
        for i, col in enumerate(cols):
            val = row[col]
            if isinstance(val, (float, int)) and col != "Modelo":
                txt = f"{val:.3f}"
            else:
                txt = str(val)
            
            pdf.cell(col_widths[i], 7, txt, 1, 0, 'C', is_best)
        pdf.ln()
        
    # 4. ROC Curve (Optional)
    if roc_plot_path and os.path.exists(roc_plot_path):
        pdf.ln(10)
        # Check if enough space is available (approx 100 units for title + image)
        # Standard A4 height is ~297. If Y > 200, we probably need a new page.
        if pdf.get_y() > 200:
            pdf.add_page()
            
        pdf.chapter_title(current_t["roc"])
        # Center the image
        # Page width 210, margins 10 -> usable 190. Image width e.g. 140
        x_pos = (210 - 150) / 2
        pdf.image(roc_plot_path, x=x_pos, w=150)
        
    # Handle output (fpdf vs fpdf2)
    try:
        # Use simple output() first, typical for fpdf2 to get bytearray if no dest
        res = pdf.output()
        if isinstance(res, (bytes, bytearray)):
            return bytes(res)
        elif isinstance(res, str):
             # classic fpdf returns str if dest not specified or 'S'
             # but standard output() prints to stdout. 
             # Let's try explicit dest='S' if simple output failed to give bytes
             pass 
    except Exception:
        pass
        
    # Fallback/Safe mode
    res = pdf.output(dest='S')
    if isinstance(res, str):
        return res.encode('latin-1')
    return bytes(res)

def generate_prediction_report(results_df, stats, model_name="QSAR Model", logo_path="assets/logo.png", lang="English"):
    pdf = PDFReport(logo_path=logo_path, title="Virtual Screening / Prediction Report")
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Simple localization for prediction report
    loc = {
        "English": {
            "summary": "1. Virtual Screening Summary",
            "hits": "2. Top Active Hits (Inside AD)",
            "scaffolds": "3. Principal Scaffolds (Active Hits)",
            "scaffolds_desc": "The following scaffolds are the most frequent among the predicted active molecules. These represent the core structural frameworks of your top hits.",
            "freq": "Frequency: "
        },
        "Português": {
            "summary": "1. Resumo da Triagem Virtual",
            "hits": "2. Melhores Hits Ativos (Dentro do AD)",
            "scaffolds": "3. Principais Escafolds (Ativos)",
            "scaffolds_desc": "Os seguintes escafolds são os mais frequentes entre as moléculas previstas como ativas. Eles representam a estrutura básica (core) dos seus melhores hits.",
            "freq": "Frequência: "
        },
        "Deutsch": {
            "summary": "1. Zusammenfassung des virtuellen Screenings",
            "hits": "2. Top-Aktiv-Treffer (Innerhalb AD)",
            "scaffolds": "3. Hauptgerüste (Aktive Treffer)",
            "scaffolds_desc": "Die folgenden Gerüste (Scaffolds) kommen am häufigsten unter den vorhergesagten aktiven Molekülen vor.",
            "freq": "Häufigkeit: "
        }
    }
    t = loc.get(lang, loc["English"])
    
    # 1. Executive Summary
    pdf.chapter_title(t["summary"])
    
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 5, f"Model Used: {model_name}")
    pdf.ln(5)
    
    total_processed = stats.get('total_processed', 0)
    total_active = stats.get('total_active', 0)
    
    pdf.add_metric_card("Total Molecules:", total_processed)
    pdf.add_metric_card("Predicted Actives:", total_active)
    
    if 'AD_Status' in results_df.columns:
        inside = len(results_df[results_df['AD_Status'] == 'Inside'])
        outside = len(results_df[results_df['AD_Status'] == 'Outside'])
        pdf.add_metric_card("Inside AD:", f"{inside} (Reliable)")
        pdf.add_metric_card("Outside AD:", f"{outside} (Unreliable)")
    
    pdf.ln(5)
    
    # Explain Applicability Domain
    pdf.set_fill_color(255, 240, 240) # Light red
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, "  Applicability Domain (AD) Note", 0, 1, 'L', 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 5, "Molecules 'Outside' the AD are structurally different from the model's training set. Predictions for these molecules should be interpreted with caution, even if predicted as 'Active' with high confidence.")
    pdf.ln()

    # 2. Top Active Hits
    pdf.chapter_title(t["hits"])
    
    active_hits = results_df[results_df['Predicted_Class'] == 1]
    if 'AD_Status' in active_hits.columns:
        active_hits = active_hits[active_hits['AD_Status'] == 'Inside']
        
    if active_hits.empty:
        pdf.set_font('Arial', 'I', 11)
        pdf.cell(0, 10, "No Active hits found inside the Applicability Domain.", 0, 1)
    else:
        # Sort by confidence
        active_hits = active_hits.sort_values(by='Probability_Active', ascending=False).head(40) # Max 40 in report
        
        # Table Header
        pdf.set_font('Arial', 'B', 9)
        pdf.set_fill_color(200, 200, 200)
        
        has_id = 'ID' in active_hits.columns or 'Molecule ChEMBL ID' in active_hits.columns
        id_col = 'Molecule ChEMBL ID' if 'Molecule ChEMBL ID' in active_hits.columns else ('ID' if 'ID' in active_hits.columns else 'SMILES')
        
        pdf.cell(50, 7, "ID / SMILES (Truncated)", 1, 0, 'C', 1)
        pdf.cell(30, 7, "Confidence", 1, 0, 'C', 1)
        pdf.cell(30, 7, "AD Status", 1, 0, 'C', 1)
        if 'AD_Distance' in active_hits.columns:
            pdf.cell(30, 7, "AD Distance", 1, 1, 'C', 1)
        else:
            pdf.ln()
            
        # Table Rows
        pdf.set_font('Arial', '', 8)
        for _, row in active_hits.iterrows():
            val_id = str(row[id_col])[:30]
            val_conf = f"{row.get('Probability_Active', 0):.3f}"
            val_ad = str(row.get('AD_Status', 'N/A'))
            
            pdf.cell(50, 6, val_id, 1, 0, 'C')
            pdf.cell(30, 6, val_conf, 1, 0, 'C')
            pdf.cell(30, 6, val_ad, 1, 0, 'C')
            if 'AD_Distance' in row:
                pdf.cell(30, 6, f"{row['AD_Distance']:.3f}", 1, 1, 'C')
            else:
                pdf.ln()
                
        if len(results_df[results_df['Predicted_Class'] == 1]) > len(active_hits):
            pdf.ln(2)
            pdf.set_font('Arial', 'I', 8)
            pdf.cell(0, 5, f"* Only showing top {len(active_hits)} hits. For full results, download the CSV.", 0, 1)

    # 3. Principal Scaffolds (New)
    if RDKIT_AVAILABLE and not results_df.empty:
        active_all = results_df[results_df['Predicted_Class'] == 1].copy()
        if not active_all.empty:
            # Find SMILES column
            smiles_col = None
            for c in active_all.columns:
                if "SMILES" in str(c).upper() or "SMILE" in str(c).upper():
                    smiles_col = c
                    break
            
            if smiles_col:
                scaffolds = []
                for smi in active_all[smiles_col]:
                    try:
                        mol = Chem.MolFromSmiles(str(smi))
                        if mol:
                            scaff = MurckoScaffold.GetScaffoldForMol(mol)
                            scaff_smi = Chem.MolToSmiles(scaff)
                            if scaff_smi:
                                scaffolds.append(scaff_smi)
                    except:
                        continue
                
                if scaffolds:
                    common_scaffolds = Counter(scaffolds).most_common(6) # Show top 6
                    
                    pdf.add_page()
                    pdf.chapter_title(t["scaffolds"])
                    pdf.set_font('Arial', '', 11)
                    pdf.multi_cell(0, 5, t["scaffolds_desc"])
                    pdf.ln(5)
                    
                    # Create a grid for scaffolds
                    # 2 columns, 3 rows for 6 scaffolds
                    scaff_temp_dir = tempfile.mkdtemp()
                    
                    # Table headers if needed or just images
                    col_w = 90
                    img_size = 60
                    
                    for i, (scaff_smi, count) in enumerate(common_scaffolds):
                        try:
                            scaff_mol = Chem.MolFromSmiles(scaff_smi)
                            img_path = os.path.join(scaff_temp_dir, f"scaff_{i}.png")
                            Draw.MolToFile(scaff_mol, img_path, size=(300, 300))
                            
                            # Calculate position
                            row = i // 2
                            col = i % 2
                            x = 15 + col * (col_w + 10)
                            y = pdf.get_y()
                            
                            pdf.image(img_path, x=x, y=y, w=img_size)
                            # Label below image
                            pdf.set_xy(x, y + img_size + 2)
                            pdf.set_font('Arial', 'B', 10)
                            pdf.cell(img_size, 5, f"{t['freq']}{count}", 0, 0, 'C')
                            
                            # If it's the second column or the last item, move to next "row" in PDF
                            if col == 1 or i == len(common_scaffolds) - 1:
                                if col == 1:
                                    pdf.ln(img_size + 15)
                                elif i == len(common_scaffolds) - 1:
                                     pdf.ln(img_size + 15)
                        except Exception as e:
                            # st.error(f"Error drawing scaffold: {e}")
                            pass
                    
                    # Cleanup
                    import shutil
                    shutil.rmtree(scaff_temp_dir, ignore_errors=True)

    try:
        res = pdf.output(dest='S')
        if isinstance(res, str):
            return res.encode('latin-1')
        return bytes(res)
    except Exception:
        # Fallback if something fails
        pass
    
    return b""
